# Default values for node-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: platof/node-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.2"

ports:
  containerPort: 8080

livenessProbe:
  path: /health
  port: 8080

readinessProbe:
  path: /health
  port: 8080

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: node-server.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
     cpu: 100m
     memory: 512Mi
  requests:
     cpu: 100m
     memory: 256Mi
